#pragma once

//
// This file contains all IDs of game assets
//

#define ID_TEX_JASON 0
#define ID_TEX_ENEMY 10

#define OBJECT_TYPE_JASON 0
#define OBJECT_TYPE_BRICK 1
#define OBJECT_TYPE_AUTOMOVER 2
#define OBJECT_TYPE_WALKER 3
#define OBJECT_TYPE_SOPHIA 4

#pragma region JASON

#define ID_SPRITE_JASON 10000
#define ID_SPRITE_JASON_BIG (ID_SPRITE_JASON + 1000)
#define ID_SPRITE_JASON_BIG_IDLE (ID_SPRITE_JASON_BIG + 100)
#define ID_SPRITE_JASON_BIG_IDLE_LEFT (ID_SPRITE_JASON_BIG_IDLE + 10)
#define ID_SPRITE_JASON_BIG_IDLE_RIGHT (ID_SPRITE_JASON_BIG_IDLE + 20)

#define ID_SPRITE_JASON_BIG_WALKING (ID_SPRITE_JASON_BIG + 200)
#define ID_SPRITE_JASON_BIG_WALKING_LEFT (ID_SPRITE_JASON_BIG_WALKING + 10)
#define ID_SPRITE_JASON_BIG_WALKING_RIGHT (ID_SPRITE_JASON_BIG_WALKING + 20)
#define ID_SPRITE_JASON_BIG_RUNNING (ID_SPRITE_JASON_BIG + 300)
#define ID_SPRITE_JASON_BIG_RUNNING_LEFT (ID_SPRITE_JASON_BIG_RUNNING + 10)
#define ID_SPRITE_JASON_BIG_RUNNING_RIGHT (ID_SPRITE_JASON_BIG_RUNNING + 20)
#define ID_SPRITE_JASON_BIG_JUMP (ID_SPRITE_JASON_BIG + 400)
#define ID_SPRITE_JASON_BIG_JUMP_WALK (ID_SPRITE_JASON_BIG_JUMP + 10)
#define ID_SPRITE_JASON_BIG_JUMP_WALK_LEFT (ID_SPRITE_JASON_BIG_JUMP_WALK + 2)
#define ID_SPRITE_JASON_BIG_JUMP_WALK_RIGHT (ID_SPRITE_JASON_BIG_JUMP_WALK + 6)
#define ID_SPRITE_JASON_BIG_JUMP_RUN (ID_SPRITE_JASON_BIG_JUMP + 20)
#define ID_SPRITE_JASON_BIG_JUMP_RUN_LEFT (ID_SPRITE_JASON_BIG_JUMP_RUN + 2)
#define ID_SPRITE_JASON_BIG_JUMP_RUN_RIGHT (ID_SPRITE_JASON_BIG_JUMP_RUN + 6)
#define ID_SPRITE_JASON_BIG_SIT (ID_SPRITE_JASON_BIG + 500)
#define ID_SPRITE_JASON_BIG_SIT_LEFT (ID_SPRITE_JASON_BIG_SIT + 10)
#define ID_SPRITE_JASON_BIG_SIT_RIGHT (ID_SPRITE_JASON_BIG_SIT + 20)
#define ID_SPRITE_JASON_BIG_BRACE (ID_SPRITE_JASON_BIG + 600)
#define ID_SPRITE_JASON_BIG_BRACE_LEFT (ID_SPRITE_JASON_BIG_BRACE + 10)
#define ID_SPRITE_JASON_BIG_BRACE_RIGHT (ID_SPRITE_JASON_BIG_BRACE + 20)

#define ID_SPRITE_JASON_DIE (ID_SPRITE_JASON + 3000)

#pragma endregion

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_AUTOMOVER 30000
#define ID_SPRITE_AUTOMOVER_WALK (ID_SPRITE_AUTOMOVER + 1000)
#define ID_SPRITE_AUTOMOVER_DIE (ID_SPRITE_AUTOMOVER + 2000)

#define ID_MAP_TEXTURE 9000